name: Build Compat Matrix HTML

on:
  push:
    branches: [ '*' ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  setup-and-build:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install packages
        run: | 
          apt-get update && apt-get install -y pandoc python3-pip && \
          pip3 install -r ./src/requirements.txt
      - name: Build compat matrix
        run: ./src/rebuild_results_certs_r3.sh
      # - name: Archive Compatibility Matrix
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: compatibility-matrix
      #     path: ./output/
