name: Artifact validation

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  oqs_validation:
    runs-on: ubuntu-latest
    container: openquantumsafe/oqs-ossl3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: ./src/test_certs_r3.sh
      - name: Archive Compatibility Matrix
        uses: actions/upload-artifact@v4
        with:
          name: compatibility-matrix
          path: ./docs/*.html
  build_results_html:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install packages
        run: | 
          apt-get update && apt-get install -y pandoc lsb-release
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python -m pip install -r src/requirements.txt
      - name: Build compat matrix
        run: ./src/rebuild_results_certs_r3.sh
      - name: Archive Compatibility Matrix For Download
        uses: actions/upload-artifact@v4
        with:
          name: compatibility-matrix
          path: ./docs/*.html
# TODO -- bundle the html pages for downloa
# TODO -- publish the html pages to ghpages
